###################  端口配置 ###################
server:
  port: 8989
  servlet:
    context-path: /modeler


###################  spring配置  ###################
spring:
  datasource:
    url: jdbc:mysql://47.104.7.87:3306/flow?allowMultiQueries=true&useUnicode=true&nullCatalogMeansCurrent=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


#spring:
#    aop:
#        auto: true
#        proxy-target-class: true
#    datasource:
#       url: jdbc:h2:mem:act
#       username : sa
#       password :
#       type: com.alibaba.druid.pool.DruidDataSource
#       driver-class-name : org.h2.Driver
#    cache:
#       type: simple
#

flowable:
    common:
      app:
        idm-url: http://localhost:8989/flowable-idm
        idm-admin:
          user: admin
          password: test

    async-executor-activate: false #关闭定时任务JOB
    database-schema-update: true

